# Setup
title:               Daniel Santiago Alvarez
tagline:             ''
description:         'Math PhD student @ <a href="https://www.math.harvard.edu/" target="_blank">MIT</a>.'
url:                 https://dasantiag.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Daniel Santiago Alvarez
  url:               https://dasantiag.github.io
  email:             dsantiagoalvarez@math.harvard.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
